name: G-PvP
version: 1.0
main: com.farahsoftware.gpvp
api-version: 1.20
commands:
  gpvp:
    description: Main G-PvP Command
    usage: /gpvp <addkit | setcheckpoint | getloot | help>
    Alias: [gpvp]
    permission:
    gpvp.loot:
        description: Allows players to retrieve their loot from PvP.
        default: true
    gpvp.admin:
      description: Allows admins to set checkpoints and add kits.
      default: op